### ISSUE TITLE
Links to PDM do not include extra metadata to display PD usage guidelines

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/EuropeanaLicensingFramework#4] opened 2017-10-19 13:00 UTC
Originally links to the public domain mark contained in the metadata of digital objects on Europeana provided extra metadata that would result in the PDM displaying a link to our PD usage guidelines
at http://www.europeana.eu/portal/rights/public-domain.html. This extra metadata is currently not provided and as a result the original functionality is broken.

**Comment by juliafallon** [comment] 2017-10-25 11:40
Can you see if this is the providers not providing the data or something EF is doing?

**Comment by paul2keller** [comment] 2017-10-25 11:54
this is something that Europeana should do (the extra metadata is the same for each occasion of the PDM so there is not need to provide data from the data providers. I has made a demonstration page for this back in the days which can be found here: 

http://www.voyantes.net/test/pdm.html

the link to PDM on this page is formatted in a way that should allow the PDM to pull in the extra metadata, but it appears that this functionality may be broken on the CC side. @mzeinstra can you take a look at this?

**Comment by juliafallon** [comment] 2017-11-28 14:10
Is there any news on this @mzeinstra ?

**Comment by mzeinstra** [comment] 2017-11-28 14:41
@juliafallon Europeana is now HTTPS by default (according to my test).

As far as I can recall this functionality of the Creative Commons deeds will be less and less possible since most sites are switching over to HTTPS by default instead of HTTP. With HTTPS you can no longer see where your traffic is coming from. 

I used the same test for Creative Commons and it seems that they have switched over to HTTPS by default too.

Since Creative Commons is now also HTTPS by default too, I cannot reproduce the wanted behaviour via @paul2keller test-site. @paul2keller Do you have a working screenshot for us?

**Comment by mzeinstra** [comment] 2017-11-28 21:53
Just had a confirmation by Creative Commons' developer that indeed they moved to HTTPS by design, and won't serve any HTTP pages anymore. This breaks the tool. 

I am closing this ticket as we cannot fix this.

**Closed by mzeinstra** 2017-11-28 21:53 UTC
Labels: bug

**Comment by paul2keller** [comment] 2017-11-29 16:07
have complained to this at CC but I guess this means that this functionality is gone for good. we will need to reflect this when we review the DEA

**Comment by paul2keller** [comment] 2018-01-08 20:52
CC has now formally retired the CC scrapper functionality which is documented here: https://wiki.creativecommons.org/wiki/Metadata_Scraper
